version: '3.8'

services:
  postgres:
    image: 'postgres:${POSTGRES_VERSION?err}'
    container_name: auth-api
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?err}
      POSTGRES_USER: ${POSTGRES_USER:?err}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
    ports:
      - '${POSTGRES_PORT?err}:5432'
